from .google import GoogleSearch
from .googlescholar import GoogleScholarSearch
from .yahoo import YahooSearch
from .bing import BingSearch
from .duckduckgo import DuckDuckGoSearch
from .aol import AolSearch
from .yandex import YandexSearch
from .stackoverflow import StackOverflowSearch
from .baidu import BaiduSearch
from .github import GitHubSearch
from .ask import AskSearch
from .youtube import YouTubeSearch
from .myanimelist import MyAnimeListSearch
from .coursera import CourseraSearch